import {StyleSheet, Platform, Dimensions} from 'react-native';
import {size, family} from '../fonts';
import {colors} from '../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.blue,
  },
  flex: {
    flex: 1,
  },
  txbold: {
    fontFamily: family.semibold,
  },
  lotus_sty: {
    width: 280,
    height: 297,
    resizeMode: 'contain',
  },
  lotus_sty_intro: {
    width: 180,
    height: 180,
    resizeMode: 'contain',
  },

  row: {flexDirection: 'row'},
  pd20: {padding: 20},
  pd10: {padding: 10},
  pdT0: {paddingTop: 0},
  pd_H20: {paddingHorizontal: 15},
  mt_v: {marginVertical: 10},
  mt_B: {marginBottom: 15},
  ml_15: {marginLeft: 15},
  mt_t10: {
    marginTop: 10,
  },
  mh_10: {marginHorizontal: 10},
  mr_10: {marginRight: 15},

  wdh60: {width: '60%'},
  wdh40: {width: '40%'},
  wdh20: {width: '20%'},
  wdh30: {width: '30%'},
  wdh10: {width: '10%'},
  wdh15: {width: '15%'},
  wdh55: {width: '55%'},
  wdh70: {width: '70%'},
  wdh50: {width: '50%'},
  wdh48: {width: '48%'},
  wdh75: {width: '75%'},
  wdh80: {width: '80%'},
  wdh90: {width: '90%'},
  wdh65: {width: '65%'},
  wdh85: {width: '85%'},

  center: {justifyContent: 'center', alignItems: 'center', flex: 1},
  align_C: {alignItems: 'center'},
  align_E: {alignItems: 'flex-end'},
  justify_C: {justifyContent: 'center'},
  justify: {justifyContent: 'flex-end'},
  justify_S: {justifyContent: 'space-between'},
  justify_A: {justifyContent: 'space-around'},

  txAlignC: {textAlign: 'center'},
  txAlignJ: {textAlign: 'justify'},
  txAlignR: {textAlign: 'right'},
  txAlignL: {textAlign: 'left'},

  txCap: {textTransform: 'capitalize'},
  txUpr: {textTransform: 'uppercase'},

  txDecor: {textDecorationLine: 'underline'},

  tx10: {
    fontSize: 10,
    color: colors.white,
    fontFamily: family.regular,
  },
  tx12: {
    fontSize: size.label,
    color: colors.white,
    fontFamily: family.light,
  },
  question_heading: {
    fontSize: size.label,
    color: colors.black,
    fontFamily: family.light,
    letterSpacing: 1,
    textAlign: 'justify',
  },
  tx13: {
    fontSize: size.subtitle,
    color: colors.white,
    fontFamily: family.regular,
  },
  tx14: {
    fontSize: size.subtitle,
    color: colors.white,
    fontFamily: family.regular,
    textAlign: 'justify',
    letterSpacing: 1,
  },
  tx18: {
    fontSize: size.subheading,
    color: colors.white,
    fontFamily: family.medium,
    textAlign: 'left',
  },
  tx16: {
    fontSize: size.title,
    color: colors.white,
    fontFamily: family.regular,
    lineHeight: 24,
    letterSpacing: 0.3,
  },
  tx16Tip: {
    fontSize: size.title,
    color: colors.black,
    fontFamily: family.regular,
    // lineHeight: 24,
    letterSpacing: 1,
    textAlign: 'justify',
  },
  error: {
    color: colors.danger,
    fontSize: 12,
    marginLeft: 15,
  },
  btntxt: {
    fontSize: size.subtitle,
    color: colors.blue,
    fontFamily: family.medium,
    letterSpacing: 1,
    textAlign: 'center',
  },
  tx20: {
    fontSize: size.heading,
    color: colors.white,
    fontFamily: family.medium,
  },
  tx22: {
    fontSize: 22,
    color: colors.white,
    fontFamily: family.medium,
  },
  logoSty: {
    width: 243,
    height: 160,
    resizeMode: 'contain',
  },
  seprator: {
    height: 1,
    backgroundColor: colors.white,
    // marginTop:-20,
    width: 200,
    alignSelf: 'center',
  },
  footerSty: {
    position: 'absolute',
    bottom: 2,
    left: 0,
    right: 0,
  },
  box: {
    width: 53,
    height: 31,
    backgroundColor: colors.white,
  },
  inputsty: {
    borderWidth: 1.5,
    borderColor: colors.skyblue,
    marginHorizontal: 10,
  },
  iconsty: {
    width: 44,
    height: 44,
    resizeMode: 'contain',
  },

  fotr_logoSty: {
    width: 74,
    height: 55,
  },
  link_txt: {
    fontFamily: family.medium,
    fontSize: size.title,
    color: colors.link,
    lineHeight: 32,
  },
  picker_sty: {
    borderWidth: 1.5,
    borderColor: colors.white,
    borderRadius: 8,
  },
  black_box: {
    paddingHorizontal: 10,
    paddingVertical: 20,
    borderRadius: 10,
    backgroundColor: colors.textBox,
    flex: 1,

    // elevation: 1,
  },
  tringle: {
    //To make Triangle Shape
    width: 0,
    height: 0,
    borderLeftWidth: 10,
    borderRightWidth: 10,
    borderBottomWidth: 20,
    borderStyle: 'solid',
    backgroundColor: 'transparent',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: colors.black_box,
    transform: [{rotate: '-90deg'}],
    marginTop: '5%',
  },
  bell_count: {
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0,
   
    
  },
  badgeVisible: {
    opacity: 1,
  },
  animatedCir_1: {
    width: 146,
    height: 146,
    borderRadius: 73,
    borderWidth: 2,
    borderColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
  animatedCir_2: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: colors.white,
    // justifyContent: 'center',
    alignItems: 'center',
  },
  animatedCir_2Pos: {left: 85, top: -25},
  mansa_container: {
    position: 'absolute',
    bottom: 70,
    left: 30,
    // alignSelf:"center"
  },
  callout: {
    width: 0,
    height: 0,
    borderLeftWidth: 70,
    borderRightWidth: 70,
    borderBottomWidth: 90,
    borderStyle: 'solid',
    backgroundColor: 'transparent',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#FFE9C6',
    transform: [{rotate: '-180deg'}],
    marginLeft: '13%',
    marginTop: -30,
  },
  callout_con: {top: '45%', position: 'absolute', left: '40%'},
  mansa_chat: {
    width: 190,
    height: 190,
    borderRadius: 95,
    backgroundColor: '#FFE9C6',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 15,
  },
  contact_footer: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginHorizontal: 15,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.white,
    borderRadius: 10,
    width: '95%',
    alignItems: 'center',
  },
  thumbnailSty: {
    width: 80,
    height: 100,
  },
  pamphlateSty: {
    width: 70,
    height: 120,
  },
  dis_img: {
    width: 200,
    height: 200,
    resizeMode: 'contain',
    // tintColor:colors.blue
  },
  notifiCard: {
    borderColor: colors.grey,
    borderWidth: 0.5,
    backgroundColor: colors.white,
    borderRadius: 5,
    padding: 10,
    elevation: 0.5,
    marginBottom: 10,
  },
  shadowProp: {
    elevation: 1,
    shadowColor: colors.black,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.5,
    shadowRadius: 4,
  },
});
