const colors = {
  danger: '#E80000',
  black: '#000',
  white: '#fff',
  skyblue: '#80CDDB',
  grey: '#ccc',
  lightText: '#777',
  blue: '#050448',
  red: '#AF0000',
  pink: '#EF5DA8',
  purple: '#AEAFF7',
  lightBlue: '#1A1881',
  orange: '#F09E54',
  footer_bg: '#020074',
  link: '#1F90A5',
  card_border: '#4FE3FE',
  drawerCircle: '#16A9B1A1',
  textBox: '#252836',
  dashboard_bg: '#14243E',
  circle_1: '#2E667F',
  circle_2: '#4A9CB9',
  warning: '#F8A435',

  frozy: '#D3FFF5',
  lightFrozy: '#02BD94',
};

const images = {
  lotus: require('../../images/logo.png'),
  lotus_gif: require('../../images/lotus_gif.gif'),
  logo_txt: require('../../images/Hindi_text.png'),
  footer_logo: require('../../images/footer_logo.png'),
  mobile: require('../../images/mobile.png'),
  guest: require('../../images/guest.png'),
  user: require('../../images/user.png'),
  menu: require('../../images/menu.png'),
  mansa: require('../../images/mansa.png'),
  self_assessment: require('../../images/self_assessment.png'),
  Ellipse: require('../../images/Ellipse.png'),
  video: require('../../images/video.png'),

  IEC: require('../../images/IEC.png'),
  mankasha: require('../../images/mankasha.png'),
  telemanas: require('../../images/telemanas.png'),
  myth: require('../../images/myth.png'),
  new: require('../../images/new.png'),
  adhd: require('../../images/adhd.png'),
  asd: require('../../images/asd.png'),
  int_dis: require('../../images/int_dis.png'),
  learning: require('../../images/learning.png'),
  address: require('../../images/MankashaBg.jpeg'),
  call: require('../../images/call.png'),
  mail: require('../../images/mail.png'),
  satya: require('../../images/satya.png'),
  tele_bottom: require('../../images/Tele_bottom.png'),
  tele_top: require('../../images/tele_manas_top.png'),
  netlink_logo: require('../../images/Netlinklogo.jpg'),
};

export {colors, images};
