import {environment} from '../constant';

class Endpoints {
  baseUrl = environment.baseUrl;
  LOGIN = this.baseUrl + 'OTP/send';
  OTP = this.baseUrl + 'OTP/verify/';
  Get_Occupation = this.baseUrl + 'getAllOccupation/';
  SAVE_USER = this.baseUrl + 'saveUser';
  GET_QuestionById = this.baseUrl + 'getAgeQuestionByID';
  GET_Guideline = this.baseUrl + 'getAllGuide';
  POST_FEEDBACK = this.baseUrl + 'saveFeedback';
  ADMIN_AUTH = this.baseUrl + 'authenticate';
  GET_AGE = this.baseUrl + 'getallAge/';
  GET_VIDEO = this.baseUrl + 'getAllVideo/';
  GET_GQTIPS = this.baseUrl + 'GQTips';
  GET_ALLTIPS = this.baseUrl + 'getTipByAgeId/';
  GET_FEELINGS = this.baseUrl + 'feelingMasters/';
  GET_SUB_FEEL = this.baseUrl + 'getsubfeelingbyId/';
  GET_OTHER_FEEL = this.baseUrl + 'getSubFeelingQuestions/';
  GET_FEEL_QUES = this.baseUrl + 'getAllQuestionBysubFeelingId/';
  GET_MYTH = this.baseUrl + 'myths/';
  GET_SUGGEST_VDO = this.baseUrl + 'video/';
  GET_MAGAZINES = this.baseUrl + 'EMagazine/getAllMagazine/';
  GET_MAG_BY_FEEL = this.baseUrl + 'EMagazine/magazine/';
  GET_Pamplate = this.baseUrl + 'getAllPamplets';
  GET_Broucher = this.baseUrl + 'getAllBrochures';
  GET_USER_PROFILE = this.baseUrl + 'getUserById/';
  UPDATE_USER = this.baseUrl + 'updateGuest/';
  ADD_PAMPLATE = this.baseUrl + 'upload/pamplet';
  GET_PAMPLATE_BYID = this.baseUrl + 'getPamplet/';
  DELETE_PAMPLATE = this.baseUrl + 'delete/';
  UPDATE_PAMPLATE = this.baseUrl + 'update/';
  ADD_BROUCHER = this.baseUrl + 'upload/brochure';
  DELETE_BROUCHER = this.baseUrl + 'deleteBrochure/';
  UPDATE_BROUCHER = this.baseUrl + 'updateBrochure/';
  GET_BROUCHER_BYID = this.baseUrl + 'getBrochure/';
  UPDATE_GUIDELINE = this.baseUrl + 'updateGuideline/';
  ADD_GUIDELINE = this.baseUrl + 'saveGuideLines';
  GET_GUIDELINE_BYID = this.baseUrl + 'getGuideline/';
  DELETE_GUIDELINE = this.baseUrl + 'DeleteGuideLine/';
  ADD_VDO = this.baseUrl + 'saveVideo';
  UPDATE_VDO = this.baseUrl + 'updateVideo/';
  GET_VDOBYID = this.baseUrl + 'getVideo/';
  DELETE_VDO = this.baseUrl + 'DeleteVideo/';
  ADD_FEELINGS = this.baseUrl + 'addFeelings';
  DELETE_FEELING = this.baseUrl + 'DeleteFeeling/';
  UPDATE_FEELINGS = this.baseUrl + '';
  GET_FEELINGSBYID = this.baseUrl + '';
  ADD_SUBFEELINGS = this.baseUrl + 'saveSubFeelingMaster';
  EDIT_SUBFEELINGS = this.baseUrl + '';
  DELETE_SUBFEELING = this.baseUrl + 'deleteSubFeeling/';
  GET_FAQ = this.baseUrl + 'FAQs';
  ADD_MAGAZINES = this.baseUrl + 'EMagazine/upload/magazine';
  ADD_QUES = this.baseUrl + 'addQuestionFeelingMaster';
  DELETE_FEELQUES = this.baseUrl + 'DeleteFeelingQuestion/';
  ADD_AGE = this.baseUrl + 'saveAgeMaster';
  DELETE_Age = this.baseUrl + 'DeleteAgeMember/';
  GET_AGE_REPORT = this.baseUrl + 'getReportByAge'; //AdultScore
  GET_OCCUPATION_REPORT = this.baseUrl + 'getReportByOccupation';//Occupationexcel
  SCORE_ADULT_REPORT = this.baseUrl + 'getReportByAdult'; //ScoreAdult
  GET_Gender_REPORT = this.baseUrl + 'getReportByGender'; //GenderExcel
  GEOLOCATION_REPORT = this.baseUrl + 'getReportByLocation';//GeoLocationExcel
  FEEDBACK_REPORT = this.baseUrl + 'getReportByFeedback'; //feedbackandSuggestion
  LOGIN_REPORT = this.baseUrl + 'getReportByLogin'; //LoginCount
  ALL_SUBFEEL = this.baseUrl + 'getAllSubFeeling';
  GET_AGE_REPORT_FILTER = this.baseUrl + 'AdultScorefilter';
  GET_OCCUPATION_FILTER_REPORT = this.baseUrl + 'OccupationexcelFeeling';
  CHILD_REPORT = this.baseUrl + 'getReportByChild';//ChildReport
  SAVE_TIP = this.baseUrl + 'saveTipMaster';
  GET_TIPS_BY_ID = this.baseUrl + 'getTipByAgeId/';
  SAVE_SCORE_GQ = this.baseUrl + 'saveAgeScoreUser';
  SAVE_SCORE_SUBFEEL = this.baseUrl + 'saveSubFeelingScoreUser';
  SCORE_DESC_AGE = this.baseUrl + 'ScoreRangeDescriptionAge';
  SCORE_DESC_FEEL = this.baseUrl + 'ScoreRangeDescriptionFeel';
  SAVE_CALLBACK = this.baseUrl + 'saveRequestCallBack';
  GET_DISTRICT = this.baseUrl + 'getAllDistrictlist';
  GET_ROLE = this.baseUrl + 'getRoleName';
  GET_ADMIN_PROFILE = this.baseUrl + 'getUserbyContact/9755638573';
  UPDATE_ADMIN_PROFILE = this.baseUrl + 'saveUserInfo';
  SAVE_PASSWORD = this.baseUrl + 'changeRolepassword';
  GET_VIDEO_BYFEEL = this.baseUrl + 'getFeelingVideo/';
  GET_MAGAZINES_BYFEEL = this.baseUrl + 'getFeelingwiseMagazie/';
  GET_TIPSBYFEEL = this.baseUrl + 'getTipsbyfeeling/';
  TELEMANAS = this.baseUrl + 'telemanas';
  GET_VERSION = this.baseUrl + 'getAppversion';
  GET_HISTORY = this.baseUrl + 'UserReport';
  GET_ALL_CHILD = this.baseUrl + 'getallchildtip';
  ADULT_GENE_REPORT = this.baseUrl + 'AdultGeneralQues';
  CHILD_FURTHR_REPORT = this.baseUrl + 'getReportBySubChild';//furterGeneralQues
  GUEST_LOGIN = this.baseUrl + 'saveGuestUser';
  GET_NOTIF_COUNT = this.baseUrl + 'getNotification/';
  GET_NOTIFICATION = this.baseUrl + 'changeStatus/';
  GET_GEOLOCATION = this.baseUrl + 'getLocation/';
  Get_DISORDER = this.baseUrl + 'disorders/get';
  GET_CHILD_HISTORY = this.baseUrl + 'guardianReport'

  // npm i react-native-picker-select --legacy-peer-deps
}

export const API = new Endpoints();
